/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

/**
 *
 * @author DELL
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botonCliente = new javax.swing.JButton();
        botonsolicitud = new javax.swing.JButton();
        botonmovimientos = new javax.swing.JButton();
        botonCancelarTarjetas = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("que deseas hacer?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, -1, -1));

        botonCliente.setText("cliente");
        botonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonClienteActionPerformed(evt);
            }
        });
        getContentPane().add(botonCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        botonsolicitud.setText("solicitud");
        botonsolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonsolicitudActionPerformed(evt);
            }
        });
        getContentPane().add(botonsolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        botonmovimientos.setText("movimientos");
        botonmovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonmovimientosActionPerformed(evt);
            }
        });
        getContentPane().add(botonmovimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        botonCancelarTarjetas.setText("Cancelar tarjetas");
        botonCancelarTarjetas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarTarjetasActionPerformed(evt);
            }
        });
        getContentPane().add(botonCancelarTarjetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, -1));

        jButton5.setText("reportes");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonClienteActionPerformed
        // TODO add your handling code here:
           crearcliente crearCliente = new crearcliente();
         crearCliente.setVisible(true);

        
        
    }//GEN-LAST:event_botonClienteActionPerformed

    private void botonsolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonsolicitudActionPerformed
        // TODO add your handling code here:
         solicitudVista solicitudvista = new solicitudVista();
         solicitudvista.setVisible(true);
        
        
        
    }//GEN-LAST:event_botonsolicitudActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
           cargarArchivoVista carga = new cargarArchivoVista();
         carga.setVisible(true);

        
    }//GEN-LAST:event_formWindowClosing

    private void botonmovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonmovimientosActionPerformed
        // TODO add your handling code here:
        MovimientoVista movimiento = new MovimientoVista();
         movimiento.setVisible(true);
    }//GEN-LAST:event_botonmovimientosActionPerformed

    private void botonCancelarTarjetasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarTarjetasActionPerformed
        // TODO add your handling code here:
        cancelarTarjetaVista cancelacion = new cancelarTarjetaVista();
         cancelacion.setVisible(true);
    }//GEN-LAST:event_botonCancelarTarjetasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelarTarjetas;
    private javax.swing.JButton botonCliente;
    private javax.swing.JButton botonmovimientos;
    private javax.swing.JButton botonsolicitud;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
