/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import com.mycompany.modelos.cliente;
import com.mycompany.modelos.movimiento;
import com.mycompany.modelos.tarjeta;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import queries.QueryCliente;
import queries.QueryMovimiento;
import queries.QueryTarjeta;

/**
 *
 * @author DELL
 */
public class MovimientoVista extends javax.swing.JFrame {

    /**
     * Creates new form MovimientoVista
     */
    public MovimientoVista() {
        initComponents();
        LlenarComboNombre();
    }

    public void LlenarComboNombre() {
        // Llamar a tu query
        QueryCliente queryCliente = new QueryCliente();

        // Obtener la lista
        ArrayList<cliente> lista = queryCliente.listar();
        for (cliente listaDeClientes : lista) {
            this.comboclientes.addItem(listaDeClientes);
        }

        comboclientes.addActionListener(e -> {
            // Obtener el elemento seleccionado
            cliente clienteSeleccionado = (cliente) comboclientes.getSelectedItem();
            QueryTarjeta queryTarjeta = new QueryTarjeta();
            ArrayList<tarjeta> tarjetasPorCliente = queryTarjeta.listarTarjetaPorCliente(clienteSeleccionado.getId());

            this.tarjetasclientecombo.removeAllItems();
            for (tarjeta tarjeta : tarjetasPorCliente) {
                this.tarjetasclientecombo.addItem(tarjeta);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tarjetalable = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        movimientosCombo = new javax.swing.JComboBox<>();
        descripcionTexto = new javax.swing.JTextField();
        establecimientoTexto = new javax.swing.JTextField();
        montotexto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        clientecombo = new javax.swing.JLabel();
        comboclientes = new javax.swing.JComboBox<>();
        tarjetasclientecombo = new javax.swing.JComboBox<>();
        fondoMovimiento = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tarjetalable.setText("TARJETA");
        getContentPane().add(tarjetalable, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, -1));

        jLabel1.setText("TIPO DE MOVIMIENTO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        jLabel2.setText("DESCRIPCION");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        jLabel3.setText("ESTABLECIMIENTO");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        jLabel4.setText("MONTO");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        movimientosCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CARGO", "MONTO" }));
        getContentPane().add(movimientosCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 230, -1));
        getContentPane().add(descripcionTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 230, -1));
        getContentPane().add(establecimientoTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 160, -1));
        getContentPane().add(montotexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, -1, -1));

        jButton1.setText("ACEPTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));

        clientecombo.setText("CLIENTE");
        getContentPane().add(clientecombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        getContentPane().add(comboclientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 230, -1));

        getContentPane().add(tarjetasclientecombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 230, -1));
        getContentPane().add(fondoMovimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 512, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String tipoMovimiento = movimientosCombo.getSelectedItem().toString();
        String descripcion = descripcionTexto.getText();
        String establecimiento = establecimientoTexto.getText();
        int monto = Integer.valueOf(montotexto.getText());
        LocalDate fecha = LocalDate.now();
        tarjeta tarjetaSeleccionada = (tarjeta) this.tarjetasclientecombo.getSelectedItem();

        double dineroActual = tarjetaSeleccionada.getDinero() - monto;
        if (dineroActual >= 0) {
            
            movimiento tmp = new movimiento(-1, descripcion, monto, establecimiento, fecha, tarjetaSeleccionada.getNoDeTarjeta(),tipoMovimiento);
            QueryMovimiento queryMovimiento = new QueryMovimiento();
            boolean creado = queryMovimiento.crear(tmp);
            if (creado) {
                tarjetaSeleccionada.setDinero(dineroActual);
                QueryTarjeta queryTarjeta = new QueryTarjeta();
                queryTarjeta.actualizar(tarjetaSeleccionada);
            }

        } else {
            JOptionPane.showMessageDialog(null, "No tienes dinero");
        }

        // -----------

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovimientoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovimientoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovimientoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovimientoVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovimientoVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clientecombo;
    private javax.swing.JComboBox<cliente> comboclientes;
    private javax.swing.JTextField descripcionTexto;
    private javax.swing.JTextField establecimientoTexto;
    private javax.swing.JLabel fondoMovimiento;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField montotexto;
    private javax.swing.JComboBox<String> movimientosCombo;
    private javax.swing.JLabel tarjetalable;
    private javax.swing.JComboBox<tarjeta> tarjetasclientecombo;
    // End of variables declaration//GEN-END:variables
}
