/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import com.mycompany.modelos.SecuenciaTarjeta;
import com.mycompany.modelos.cliente;
import com.mycompany.modelos.solicitud;
import com.mycompany.modelos.tarjeta;
import com.mycompany.modelos.tipoTarjeta;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import queries.QueryCliente;
import queries.QuerySecuenciaTarjeta;
import queries.QuerySolicitud;
import queries.QueryTarjeta;
import queries.QueryTipoTarjeta;

/**
 *
 * @author DELL
 */
public class solicitudVista extends javax.swing.JFrame {

    /**
     * Creates new form solicitud
     */
    public solicitudVista() {
        initComponents();
        LlenarCombo();
        LlenarComboNombre();
    }

    public void LlenarCombo() {
        // Llamar a tu query
        QueryTipoTarjeta querytipoTarjetaa = new QueryTipoTarjeta();

        // Obtener la lista
        ArrayList<tipoTarjeta> lista = querytipoTarjetaa.listar();
        for (tipoTarjeta ttarjeta : lista) {
            this.tipodeTarjeta.addItem(ttarjeta);
        }

    }

    public void LlenarComboNombre() {
        // Llamar a tu query
        QueryCliente queryCliente = new QueryCliente();

        // Obtener la lista
        ArrayList<cliente> lista = queryCliente.listar();
        for (cliente listaDeClientes : lista) {
            this.comboNombre.addItem(listaDeClientes);
        }

        //cliente cl = (cliente)this.comboNombre.getSelectedItem();
        //cl.getId();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tipodeTarjeta = new javax.swing.JComboBox<>();
        TextoSalario = new javax.swing.JTextField();
        comboNombre = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        idsolicitud = new javax.swing.JTextField();
        fondoVistaSolicitud = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("ID");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel5.setText("Salario");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        tipodeTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipodeTarjetaActionPerformed(evt);
            }
        });
        getContentPane().add(tipodeTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 230, -1));
        getContentPane().add(TextoSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 230, -1));

        comboNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNombreActionPerformed(evt);
            }
        });
        getContentPane().add(comboNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 230, -1));

        jButton1.setText("ACEPTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, -1, -1));

        jLabel3.setText("tIpo tarjeta");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel6.setText("CREAR SOLICITUD");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));
        getContentPane().add(idsolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 220, -1));
        getContentPane().add(fondoVistaSolicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        jLabel7.setText("Nombre");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipodeTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipodeTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipodeTarjetaActionPerformed

    private void comboNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNombreActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_comboNombreActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        cliente clienteSeleccionado = (cliente) this.comboNombre.getSelectedItem();
        String nombre = clienteSeleccionado.getNombre();
        tipoTarjeta tipoTarjetaSeleccionado = (tipoTarjeta) this.tipodeTarjeta.getSelectedItem();
        String tipo = tipoTarjetaSeleccionado.getNombreTarjeta();
        int salario = Integer.parseInt(TextoSalario.getText());
        int idSolicitud = Integer.parseInt(idsolicitud.getText());
        LocalDate date2 = LocalDate.now();

        QuerySolicitud querySolicitud = new QuerySolicitud();

        if (querySolicitud.AutorizarTarjeta(salario, tipoTarjetaSeleccionado.getCredito())) {
            
            QuerySecuenciaTarjeta querySecuenciaTarjeta = new QuerySecuenciaTarjeta();
            SecuenciaTarjeta secuenciaObtenida = querySecuenciaTarjeta.ObtenerSecuencia(tipo);
            
            solicitud tmp = new solicitud(idSolicitud, salario, tipoTarjetaSeleccionado.getIdTipo(), date2, date2, "",secuenciaObtenida.getUltimoValor());
            tmp.setCliente(clienteSeleccionado);
            querySolicitud.crear(tmp);
            
            tarjeta tarjetaAutorizado = new tarjeta(secuenciaObtenida.getUltimoValor(),
                    nombre, tipoTarjetaSeleccionado.getIdTipo(), date2, "Activo", clienteSeleccionado.getId(), tipoTarjetaSeleccionado.getCredito());
            QueryTarjeta queryTarjeta = new QueryTarjeta();
            queryTarjeta.crear(tarjetaAutorizado);
            
            querySecuenciaTarjeta.actualizar(secuenciaObtenida);
            JOptionPane.showMessageDialog(null, "Felicidades, tu tarejta se ha autorizado");

        } else {
            solicitud tmp = new solicitud(-1, salario, tipoTarjetaSeleccionado.getIdTipo(), date2, null, "NO ALCANZO EL PORCENTAJE SOLICITADO",-1);
            querySolicitud.crear(tmp);
            JOptionPane.showMessageDialog(null, "No ALCANZO EL SUELDO SOLICITADO");
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
         menu regresomenu = new menu();
         regresomenu.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(solicitudVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(solicitudVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(solicitudVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(solicitudVista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new solicitudVista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextoSalario;
    private javax.swing.JComboBox<cliente> comboNombre;
    private javax.swing.JLabel fondoVistaSolicitud;
    private javax.swing.JTextField idsolicitud;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox<tipoTarjeta> tipodeTarjeta;
    // End of variables declaration//GEN-END:variables
}
